package no.synth.where.data.db

import app.cash.sqldelight.coroutines.asFlow
import app.cash.sqldelight.coroutines.mapToList
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext

/** SQLDelight-backed [TrackDao]. Queries run on [dispatcher]; multi-row writes are transactional. */
class SqlDelightTrackDao(
    private val db: WhereDatabase,
    private val dispatcher: CoroutineDispatcher = ioDispatcher,
) : TrackDao {
    private val tracksQueries = db.tracksQueries
    private val trackPointsQueries = db.trackPointsQueries

    override fun getAllTracks(): Flow<List<TrackEntity>> =
        tracksQueries.getAllTracks(::mapTrack).asFlow().mapToList(dispatcher)

    override suspend fun getPointsForTrack(trackId: String): List<TrackPointEntity> =
        withContext(dispatcher) { trackPointsQueries.getPointsForTrack(trackId, ::mapPoint).executeAsList() }

    override suspend fun insertTrack(track: TrackEntity) {
        withContext(dispatcher) { insertTrackRow(track) }
    }

    override suspend fun insertTrackPoints(points: List<TrackPointEntity>) {
        withContext(dispatcher) { db.transaction { points.forEach(::insertPointRow) } }
    }

    override suspend fun insertTrackWithPoints(track: TrackEntity, points: List<TrackPointEntity>) {
        withContext(dispatcher) {
            db.transaction {
                insertTrackRow(track)
                points.forEach(::insertPointRow)
            }
        }
    }

    override suspend fun replaceTrackWithPoints(track: TrackEntity, points: List<TrackPointEntity>) {
        // Point ids are autogenerated, so clear the old set explicitly rather than relying on the
        // INSERT OR REPLACE cascade to do it.
        withContext(dispatcher) {
            db.transaction {
                trackPointsQueries.deletePointsForTrack(track.id)
                insertTrackRow(track)
                points.forEach(::insertPointRow)
            }
        }
    }

    override suspend fun deleteTrack(trackId: String) {
        // Delete child points in the same transaction. Foreign keys are enabled, but doing it
        // explicitly keeps the behavior independent of the PRAGMA.
        withContext(dispatcher) {
            db.transaction {
                trackPointsQueries.deletePointsForTrack(trackId)
                tracksQueries.deleteTrack(trackId)
            }
        }
    }

    override suspend fun deletePointsForTrack(trackId: String) {
        withContext(dispatcher) { trackPointsQueries.deletePointsForTrack(trackId) }
    }

    override suspend fun renameTrack(trackId: String, name: String) {
        withContext(dispatcher) { tracksQueries.renameTrack(name, trackId) }
    }

    override suspend fun updateColor(trackId: String, color: String?) {
        withContext(dispatcher) { tracksQueries.updateColor(color, trackId) }
    }

    override suspend fun updateFolderForTracks(trackIds: List<String>, folder: String?) {
        withContext(dispatcher) { tracksQueries.updateFolderForTracks(folder, trackIds) }
    }

    override suspend fun renameFolder(oldName: String, newName: String) {
        withContext(dispatcher) { tracksQueries.renameFolder(newName, oldName) }
    }

    override suspend fun clearFolder(folderName: String) {
        withContext(dispatcher) { tracksQueries.clearFolder(folderName) }
    }

    override suspend fun getAllTracksOnce(): List<TrackEntity> =
        withContext(dispatcher) { tracksQueries.getAllTracksOnce(::mapTrack).executeAsList() }

    override suspend fun findTrackIdBySourceId(sourceId: String): String? =
        withContext(dispatcher) { tracksQueries.findTrackIdBySourceId(sourceId).executeAsOneOrNull() }

    private fun insertTrackRow(track: TrackEntity) = tracksQueries.insertTrack(
        id = track.id,
        name = track.name,
        startTime = track.startTime,
        endTime = track.endTime,
        isRecording = if (track.isRecording) 1L else 0L,
        folder = track.folder,
        sourceId = track.sourceId,
        color = track.color,
    )

    private fun insertPointRow(point: TrackPointEntity) = trackPointsQueries.insertTrackPoint(
        trackId = point.trackId,
        latitude = point.latitude,
        longitude = point.longitude,
        timestamp = point.timestamp,
        altitude = point.altitude,
        accuracy = point.accuracy?.toDouble(),
        orderIndex = point.orderIndex.toLong(),
    )

    private fun mapTrack(
        id: String, name: String, startTime: Long, endTime: Long?,
        isRecording: Long, folder: String?, sourceId: String?, color: String?,
    ) = TrackEntity(id, name, startTime, endTime, isRecording != 0L, folder, sourceId, color)

    private fun mapPoint(
        id: Long, trackId: String, latitude: Double, longitude: Double,
        timestamp: Long, altitude: Double?, accuracy: Double?, orderIndex: Long,
    ) = TrackPointEntity(id, trackId, latitude, longitude, timestamp, altitude, accuracy?.toFloat(), orderIndex.toInt())
}
