package no.synth.where.data.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import kotlinx.coroutines.flow.Flow

@Dao
interface TrackDao {
    @Query("SELECT * FROM tracks WHERE isRecording = 0 ORDER BY startTime DESC")
    fun getAllTracks(): Flow<List<TrackEntity>>

    @Query("SELECT * FROM track_points WHERE trackId = :trackId ORDER BY orderIndex")
    suspend fun getPointsForTrack(trackId: String): List<TrackPointEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTrack(track: TrackEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTrackPoints(points: List<TrackPointEntity>)

    @Transaction
    suspend fun insertTrackWithPoints(track: TrackEntity, points: List<TrackPointEntity>) {
        insertTrack(track)
        insertTrackPoints(points)
    }

    @Query("DELETE FROM tracks WHERE id = :trackId")
    suspend fun deleteTrack(trackId: String)

    @Query("DELETE FROM track_points WHERE trackId = :trackId")
    suspend fun deletePointsForTrack(trackId: String)

    // Overwrite a track in place. Point ids are autogenerated, so we delete the old points
    // explicitly and reinsert the new set rather than relying on the REPLACE-cascade to clear them.
    @Transaction
    suspend fun replaceTrackWithPoints(track: TrackEntity, points: List<TrackPointEntity>) {
        deletePointsForTrack(track.id)
        insertTrack(track)
        insertTrackPoints(points)
    }

    @Query("UPDATE tracks SET name = :name WHERE id = :trackId")
    suspend fun renameTrack(trackId: String, name: String)

    @Query("UPDATE tracks SET folder = :folder WHERE id IN (:trackIds)")
    suspend fun updateFolderForTracks(trackIds: List<String>, folder: String?)

    @Query("UPDATE tracks SET folder = :newName WHERE folder = :oldName")
    suspend fun renameFolder(oldName: String, newName: String)

    @Query("UPDATE tracks SET folder = NULL WHERE folder = :folderName")
    suspend fun clearFolder(folderName: String)

    @Query("SELECT * FROM tracks ORDER BY startTime DESC")
    suspend fun getAllTracksOnce(): List<TrackEntity>
}
