package no.synth.where.data.db

import kotlinx.coroutines.flow.Flow

interface TrackDao {
    fun getAllTracks(): Flow<List<TrackEntity>>

    suspend fun getPointsForTrack(trackId: String): List<TrackPointEntity>

    suspend fun insertTrack(track: TrackEntity)

    suspend fun insertTrackPoints(points: List<TrackPointEntity>)

    suspend fun insertTrackWithPoints(track: TrackEntity, points: List<TrackPointEntity>) {
        insertTrack(track)
        insertTrackPoints(points)
    }

    suspend fun deleteTrack(trackId: String)

    suspend fun deletePointsForTrack(trackId: String)

    // Overwrite a track in place. Point ids are autogenerated, so we delete the old points
    // explicitly and reinsert the new set rather than relying on the REPLACE-cascade to clear them.
    suspend fun replaceTrackWithPoints(track: TrackEntity, points: List<TrackPointEntity>) {
        deletePointsForTrack(track.id)
        insertTrack(track)
        insertTrackPoints(points)
    }

    suspend fun renameTrack(trackId: String, name: String)

    suspend fun updateColor(trackId: String, color: String?)

    suspend fun updateFolderForTracks(trackIds: List<String>, folder: String?)

    suspend fun renameFolder(oldName: String, newName: String)

    suspend fun clearFolder(folderName: String)

    suspend fun getAllTracksOnce(): List<TrackEntity>

    suspend fun findTrackIdBySourceId(sourceId: String): String?
}
