default_platform(:ios)

platform :android do
  lane :deploy do
    upload_to_play_store(
      package_name: "no.synth.where",
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      mapping: "app/build/outputs/mapping/release/mapping.txt",
      json_key: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

platform :ios do
  lane :build do
    profile_name = ENV["PROFILE_NAME"] || ""
    keychain = ENV["KEYCHAIN_PATH"]

    build_app(
      project: "iosApp/Where.xcodeproj",
      scheme: "Where",
      configuration: "Release",
      export_method: "app-store",
      output_directory: ENV["OUTPUT_DIR"] || "./build",
      output_name: "Where.ipa",
      destination: "generic/platform=iOS",
      skip_profile_detection: true,
      codesigning_identity: "iPhone Distribution: Henrik Aronsen (358L7UXVJ4)",
      xcargs: "SKIP_KOTLIN_BUILD=1 DEVELOPMENT_TEAM=358L7UXVJ4 OTHER_CODE_SIGN_FLAGS='--keychain #{keychain}'",
      export_options: {
        method: "app-store",
        teamID: "358L7UXVJ4",
        signingStyle: "manual",
        signingCertificate: "iPhone Distribution",
        uploadSymbols: true,
        provisioningProfiles: {
          "no.synth.where" => profile_name
        }
      }
    )
  end

  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )
    upload_to_testflight(
      api_key: api_key,
      app_identifier: "no.synth.where",
      ipa: ENV["IPA_PATH"],
      skip_waiting_for_build_processing: true
    )
  end
end
